### ISSUE TITLE
[Bug] On Windows, when compiling KCL, KCL Runner will panic when deleting the "*.dll" file.

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kcl#346]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

On Windows, when compiling KCL, KCLVM will panic when deleting the "*.dll" file.

### 2. What did you expect to see? (Required)

The KCL program is compiled normally and outputs YAML.

### 3. What did you see instead (Required)

```
thread 'main' panicked at '\\?\C:\AppData\Local\Temp\.tmpx10RQL\37464_1671443939813780200.dll not found, defailts: access denied. (os error 5)', runner\src\lib.rs:246:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

or

```
thread 'main' panicked at '\\?\C:\AppData\Local\Temp\.tmpx10RQL\37464_1671443939813780200.dll not found, defailts: 拒绝访问。 (os error 5)', runner\src\lib.rs:246:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### 4. What is your KusionStack components version? (Required)
v0.4.4

**Comment by zong-zhe** [comment]
I disabled the deletion of (*.dll) files in PR https://github.com/KusionStack/KCLVM/pull/345, so the Windows version of KCLVM will generate some temporary files under the directory "C:\Users\<user_name>\AppData\Local\Temp\".

<user_name> is your windows os account name. It looks like: 
```
C:\Users\<user_name>\AppData\Local\Temp\.tmpx10RQL\37464_1671443939813780200.dll
C:\Users\<user_name>\AppData\Local\Temp\.tmpx10RQL\37464_1671443939813780200.lib
C:\Users\<user_name>\AppData\Local\Temp\.tmpx10RQL\37464_1671443939813780200.exp
```


Future update will fix this and remove these temporary files soon.
